### ISSUE TITLE
Gallery images come out of order

### ISSUE THREAD

**Issue by jedicobra** [corenting/eddrit#115]
Hey I noticed that gallery images sometimes come in the wrong order, since the media_metadata part of the json endpoint isn't actually sorted. I set up a PR that seems to fix it when I run locally, could you push it to the official instance sometime? Thanks

[Here's the pr](https://github.com/corenting/eddrit/pull/114)

**Comment by corenting** [comment]
Thanks for the PR ! I merged the fix
