### ISSUE TITLE
Wide UI option

### ISSUE THREAD

**Issue by ValiumBear** [corenting/eddrit#133]
Hi.

Is it possible to add "Wide UI" option like libreddit?
By default now Wide UI is activated, but on high resolutions it's easier for me to read when it's narrow and centered.

**Comment by corenting** [comment]
Hello, thanks for the suggestion. It's indeed a missing option but it should not be difficult to add.
I can try to add something like this:
![image](https://github.com/corenting/eddrit/assets/32464/fa43d421-1655-4493-90a8-59e05e498808)
with a proper setting for it in the settings page.

**Comment by corenting** [comment]
I added an initial version of the feature, it's available in the dev version and will be in the 0.8.0 release soon.
