### ISSUE TITLE
Cookie type

### ISSUE THREAD

**Issue by ValiumBear** [corenting/eddrit#143]
When Firefox is set to auto delete cookies on exit, eddrit's cookies are wiped too (even if site is in cookie allow list).
It's because cookies are also marked as session cookie.

**Comment by corenting** [comment]
Thanks for reporting the issue! I will work on fixing the expiration of the cookies .

**Comment by corenting** [comment]
The issue was fixed in the 0.8.2 version and I updated the instance on eddrit.com
