### ISSUE TITLE
May you add a readme file?

### ISSUE THREAD

**Issue by Mr-Steal-Your-Script** [corenting/eddrit#2]
I'd like to help and contribute, but can't figure out how to get setup. Maybe you'd be nice enough to add a readme file?

**Comment by corenting** [comment]
Thank for your interest in the project ! The commit on Friday was just the initial public commit, I plan to update the README and a Dockerfile soon :) 

In the meantime to run the project you need to :
- Install [Poetry](https://python-poetry.org/)
- Run `make init` in the project folder (it will setup the virtualenv and the dependencies for the project)
- Run `make run` to launch the app through [uvicorn](https://www.uvicorn.org/).

If you run with the env variable `DEBUG=True` (through your commandline or in a .env file in the root of the project), it will enable the debug mode of starlette (display of exceptions etc...)

**Comment by Mr-Steal-Your-Script** [comment]
Okay, thanks! This guide should help me out :)

**Comment by corenting** [comment]
Added with #1 :)
