### ISSUE TITLE
redirect old.reddit.com

### ISSUE THREAD

**Issue by peterweissbier** [corenting/eddrit#215]
the redirect to old.reddit.com doesnt work, can you fix that issue please? just redirect to normal reddit and things should be fine

**Comment by corenting** [comment]
Hello, are you talking about the redirect at the bottom of a post to see all the comments ? If so I wasn't able to reproduce the issue, can you give me an example of a page on the eddrit.com instance with the issue? 

For the choice between old.reddit or the regular one I will make it configurable.

**Comment by peterweissbier** [comment]
https://eddrit.com/r/Piracy/wiki/megathread this one for example doesnt open its a normal reddit link, and the links on that site redirect to old.reddit.com and that doesnt open either

**Comment by corenting** [comment]
Thanks for the example, indeed for now eddrit doesn't support wiki links, I will fix the issue

**Comment by peterweissbier** [comment]
alright i see, thanks man!

**Comment by corenting** [comment]
The 0.9.0 version adds initial wiki support which should remove for wiki links to eddrit
