### ISSUE TITLE
Is this front-end affected by Reddit's new API change?

### ISSUE THREAD

**Issue by toprak** [corenting/eddrit#69]
As the title says.

**Comment by corenting** [comment]
Hello! Unfortunately it does seems it get rate-limited now, I'm currently adding proper error messages to notify when it's the case, especially for the eddrit.com public instance.
It seems to have around 100 calls with a reset every 5 minutes.

**Comment by corenting** [comment]
The issue has been documented in the README until maybe a rework is made to increase the rate-limit
